=== hsolbrig/ShEx/ShEx/static/xsd/ShEx.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:shex="http:/www.w3.org/shex/"
    targetNamespace="http:/www.w3.org/shex/" elementFormDefault="qualified" vc:minVersion="1.1"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning">


    <!-- Schema -->
    <xs:element name="Schema" type="shex:Schema"/>
    <xs:complexType name="Schema">
        <xs:annotation>
            <xs:documentation>A <code>Schema</code> consists of a set of labeled rules and the optional label that
                identifies the starting rule (entry point) in the Schema</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="shape" type="shex:LabeledRule" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="start" type="shex:Label" use="required"/>
    </xs:complexType>

    <!-- Labeled Rule -->
    <xs:complexType name="LabeledRule">
        <xs:annotation>
            <xs:documentation>A <code>LabeledRule</code>LabeledRule is the combination of a Rule and a label that
                uniquely identifies it within the context of a Schema. A Label can either be a URI or a Blank Node
                identifier.</xs:documentation>
        </xs:annotation>
        <xs:group ref="shex:Rule"/>
        <xs:attribute name="label" type="xs:ID"/>
    </xs:complexType>

    <!-- Rule -->
    <xs:group name="Rule">
        <xs:annotation>
            <xs:documentation>A <code>Rule</code> is a predicate that, when applied to an rdf graph, returns an
                    <code>OptValidity</code> instance</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="and" type="shex:AndRule"/>
            <xs:element name="arc" type="shex:ArcRule"/>
            <xs:element name="rarc" type="shex:RevArcRule"/>
            <xs:element name="group" type="shex:GroupRule"/>
            <xs:element name="xor" type="shex:XorRule"/>
        </xs:choice>
    </xs:group>

    <xs:complexType name="AndRule">
        <xs:annotation>
            <xs:documentation>An <code>AndRule</code> consists of a set of rules, all of which must not fail in order
                for the entire rule to pass.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:group ref="shex:Rule" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="GroupRule">
        <xs:annotation>
            <xs:documentation>A <code>GroupRule</code>GroupRule of a rule, a sequence of actions that are to be
                "executed" if the rule returns <code>PASS</code> when evaluated against a graph and an optionality
                indicator that determines whether the graph must meet the <code>Rule</code></xs:documentation>
        </xs:annotation>

        <xs:sequence>
            <xs:group ref="shex:Rule"/>
            <xs:element name="action" type="xs:anyType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="optional" type="xs:boolean" use="required"/>
    </xs:complexType>

    <xs:complexType name="ArcRule">
        <xs:annotation>
            <xs:documentation>An <code>ArcRule</code> consists of a <code>filter</code> that selects a subset of the
                target graph and a list and a <code>targetSpecification</code> that the resulting subset must meet. It
                also carries an optional minimum (<code>min</code>) and maximum (<code>max</code>) number of triples
                that can meet the filter requirements as well as a collection of <code>actions</code> that are
                "executed" if the graph passes the filter rules</xs:documentation>
        </xs:annotation>

        <xs:sequence>
            <xs:element name="p" type="shex:PredicateFilter"/>
            <xs:element name="o" type="shex:ObjectSpecification"/>
            <xs:element name="action" type="xs:anyType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attributeGroup ref="shex:occurs"/>
    </xs:complexType>

    <xs:complexType name="RevArcRule">
        <xs:annotation>
            <xs:documentation>A <code>RevArcRule</code> is the same as an <code>ArcRule</code> except that the selector
                goes from object to subject.</xs:documentation>
        </xs:annotation>

        <xs:sequence>
            <xs:element name="p" type="shex:PredicateFilter"/>
            <xs:element name="s" type="shex:SubjectSpecification"/>
            <xs:element name="action" type="xs:anyType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attributeGroup ref="shex:occurs"/>
    </xs:complexType>



    <xs:complexType name="XorRule">
        <xs:annotation>
            <xs:documentation>An <code>XorRule</code> consists of a set of rules, exactly one of which must pass for the
                entire rule to pass.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:group ref="shex:Rule" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- PredicateFilter - predicate filter -->
    <xs:complexType name="PredicateFilter">
        <xs:annotation>
            <xs:documentation>The filter for a set of predicates in a graph.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:choice>
                <xs:element name="inclusion">
                    <xs:complexType>
                        <xs:group ref="shex:IRIorStem" minOccurs="1" maxOccurs="1"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="exclusion">
                    <xs:complexType>
                        <xs:group ref="shex:IRIorStem" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <!-- ObjectSpecification - object specification -->
    <xs:complexType name="ObjectSpecification">
        <xs:annotation>
            <xs:documentation>A <code>ValueClass</code> is a predicate used against the list of targets in a
                graph</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="valueType" type="xs:anyURI"/>
            <xs:element name="inclusion">
                <xs:complexType>
                    <xs:group ref="shex:MatchValue" minOccurs="0" maxOccurs="unbounded"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="exclusion">
                <xs:complexType>
                    <xs:group ref="shex:MatchValue" minOccurs="0" maxOccurs="unbounded"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="shape" type="shex:Label"/>
        </xs:choice>
    </xs:complexType>

    <!-- SubjectSpecification - subject specification -->
    <xs:complexType name="SubjectSpecification">
        <xs:annotation>
            <xs:documentation>A <code>SubjectSpecification</code> is a predicate used against the list of subjects in a
                graph</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="inclusion">
                <xs:complexType>
                    <xs:group ref="shex:IRIorStem" minOccurs="0" maxOccurs="unbounded"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="exclusion">
                <xs:complexType>
                    <xs:group ref="shex:IRIorStem" minOccurs="0" maxOccurs="unbounded"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="shape" type="shex:Label"/>
        </xs:choice>
    </xs:complexType>

    <xs:simpleType name="Label">
        <xs:restriction base="xs:IDREF"/>
    </xs:simpleType>

    <xs:complexType name="Literal">
        <xs:sequence>
            <xs:element name="lexicalValue" type="xs:string"/>
            <xs:element name="dataType" type="xs:anyURI"/>
            <xs:element name="langTag" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="IRIstem">
        <xs:restriction base="xs:anyURI"/>
    </xs:simpleType>

    <xs:group name="IRIorStem">
        <xs:choice>
            <xs:element name="iri" type="xs:anyURI"/>
            <xs:element name="stem" type="shex:IRIstem"/>
        </xs:choice>
    </xs:group>

    <xs:group name="MatchValue">
        <xs:choice>
            <xs:element name="iri" type="xs:anyURI"/>
            <xs:element name="stem" type="shex:IRIstem"/>
            <xs:element name="literal" type="shex:Literal"/>
        </xs:choice>
    </xs:group>


    <xs:simpleType name="OptValidity">
        <xs:restriction base="xs:string">
            <xs:enumeration value="PASS"/>
            <xs:enumeration value="FAIL"/>
            <xs:enumeration value="NOMATCH"/>
            <xs:enumeration value="DUNNO"/>
            <xs:enumeration value="ERROR"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Taken from the XML Schema spec -->
    <xs:attributeGroup name="occurs">
        <xs:attribute name="min" type="xs:nonNegativeInteger" use="optional" default="1"/>
        <xs:attribute name="max" use="optional" default="1">
            <xs:simpleType>
                <xs:union>
                    <xs:simpleType>
                        <xs:restriction base="xs:nonNegativeInteger"/>
                    </xs:simpleType>
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="unbounded"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:union>
            </xs:simpleType>
        </xs:attribute>
    </xs:attributeGroup>



</xs:schema>

=== hsolbrig/ShEx/ShEx/static/xml/Issue.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xchema [
  <!ENTITY ex "http://ex.example/#">
  <!ENTITY foaf "http://foaf.example/#">
  <!ENTITY rdfs "http://www.w3.org/2000/01/rdf-schema#">
  <!ENTITY xsd "http://www.w3.org/2001/XMLSchema#">

]>
<Schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http:/www.w3.org/shex/ ../xsd/ShEx.xsd" xmlns="http:/www.w3.org/shex/"
 xmlns:ex="http://ex.example/#" xmlns:foaf="http://foaf.example/#" xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
 xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#" start="IssueShape">
    <shape label="IssueShape">
        <and>
            <arc>
                <p>
                    <inclusion>
                        <iri>&ex;state</iri>
                    </inclusion>
                </p>
                <o>
                    <inclusion>
                        <iri>&ex;assigned</iri>
                        <iri>&ex;unassigned</iri>
                    </inclusion>
                </o>
            </arc>
            <arc>
                <p>
                    <inclusion>
                        <iri>&ex;reportedBy</iri>
                    </inclusion>
                </p>
                <o>
                    <shape>UserShape</shape>
                </o>
            </arc>
            <group optional="true">
                <and>
                    <arc>
                        <p>
                            <inclusion>
                                <iri>&ex;reproducedBy</iri>
                            </inclusion>
                        </p>
                        <o>
                            <shape>EmployeeShape</shape>
                        </o>
                    </arc>
                    <arc>
                        <p>
                            <inclusion>
                                <iri>&ex;reproducedOn</iri>
                            </inclusion>
                        </p>
                        <o>
                            <valueType>&xsd;dateTime</valueType>
                        </o>
                    </arc>
                </and>
            </group>
            <arc min="0" max="unbounded">
                <p>
                    <inclusion>
                        <iri>&ex;related</iri>
                    </inclusion>
                </p>
                <o>
                    <shape>IssueShape</shape>
                </o>
            </arc>
        </and>
    </shape>
    <shape label="UserShape">
        <and>
            <xor>
                <arc>
                    <p>
                        <inclusion>
                            <iri>&foaf;name</iri>
                        </inclusion>
                    </p>
                    <o>
                        <valueType>&xsd;string</valueType>
                    </o>
                </arc>
                <and>
                    <arc min="1" max="unbounded">
                        <p>
                            <inclusion>
                                <iri>&foaf;givenName</iri>
                            </inclusion>
                        </p>
                        <o>
                            <valueType>&xsd;string</valueType>
                        </o>
                    </arc>
                    <arc>
                        <p>
                            <inclusion>
                                <iri>&foaf;familyName</iri>
                            </inclusion>
                        </p>
                        <o>
                            <valueType>&xsd;string</valueType>
                        </o>
                    </arc>
                </and>
            </xor>
            <arc>
                <p>
                    <inclusion>
                        <iri>&foaf;mbox</iri>
                    </inclusion>
                </p>
                <o>
                    <valueType>&rdfs;Resource</valueType>
                </o>
            </arc>
        </and>
    </shape>
    <shape label="EmployeeShape">
        <and>
            <arc max="unbounded">
                <p>
                    <inclusion>
                        <iri>&foaf;givenName</iri>
                    </inclusion>
                </p>
                <o>
                    <valueType>&xsd;string</valueType>
                </o>
            </arc>
            <arc>
                <p>
                    <inclusion>
                        <iri>&foaf;familyName</iri>
                    </inclusion>
                </p>
                <o>
                    <valueType>&xsd;string</valueType>
                </o>
            </arc>
            <arc min="0" max="unbounded">
                <p>
                    <inclusion>
                        <iri>&foaf;phone</iri>
                    </inclusion>
                </p>
                <o>
                    <valueType>&rdfs;Resource</valueType>
                </o>
            </arc>
            <arc>
                <p>
                    <inclusion>
                        <iri>&foaf;mbox</iri>
                    </inclusion>
                </p>
                <o>
                    <valueType>&rdfs;Resource</valueType>
                </o>
            </arc>
        </and>
    </shape>
</Schema>
